var GAME_LEVELS = [
 
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                            o                                   ",
   "                                                               xx               ",
   "                 o                                    x   x                     ",
   "                                    o      xxx        x o x                     ",
   "                xxx                 o     x!!!x       xxxxx        xxx          ",
   "            o                      xxx    x!!!x                                 ",
   "  @        o                  o            xvx                               o  ",
   "  xxx       o        o       xxx                                          xxxxxx",
   "  x x     xxxx                                              o        o    x     ",
   "  x x                xx                                     o       xx    x     ",
   "  x x      b                                     b          o             x     ",
   "  x x                                                                     x     ",
   "  xxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxx        x     ",
   "                  x    x                  x!!!!x                 x       xx     ",
   "                  x!!!!x                  x!!!!x                 x        x     ",
   "                  xxxxxx                  x!!!!x                 x        x     ",
   "                                          xxxxxx                 x        x     ",
   "                                                                 xxxxxxxxxx     ",
   "                                                                                "],
["                                                                                  x                 ",
   "                                                                                 x!x                ",
   "                                                                                x!!!x               ",
   "                                                                               x!!!!!x              ",
   "                                                                                x!!!x               ",
   "                                                                                 xvx                ",
   "                                                                                                    ",
   "                                                                                                    ",
   "                           o                                                           o            ",
   "                           o              xxxx                                        xxx           ",
   "                          xxxx                          o  o  o             o                    xxx",
   "                                      o           xxxxxxxxxxxxxxxxxxx     xxxxx                  x  ",
   "                                     o o          x                 x     x   x                  x  ",
   "                      o             xxxxx         x  !!!!!!!!!!!!!! x     x   x                  x  ", 
   "                   xxxxxxx    x                   x  !          xvx x     x   x          xxxxxxxxx  ",
   "      @           xx     x    x                   x  !!  xxxxxxxx xxx     x   x                  x  ",
   "    xxxx          x !!!! x    x             xx    x  !   x                x   x                  x  ",
   "    x  x          x !    x o  x!!!!!!!!!!!!!x     x  !!  x                x   x o                x  ",
   "    x  x          x !!!! x    xxxxxxxxxxxxxxx    ox  !   x           b    x   xxxxxxx            x  ",
   " xxxx  x       xxxx    ! x  o                    xx  !!  x   xxxxxxxxxxxxxx   x                  x  ",
   "       x   o   x    !!!! x                        x  !   x   x                x         oo       x  ",
   "       x  xxx  x    !    x                        x  !!  x o x                x        xxxx      x  ",
   "       x       x    !!!! x     b                  x  !   x   xxxxxxxxxxxxxxxxxx                  x  ",
   "       x       x       ! xxxxxxxxxxxx!!!xxxxxxxxxxx  !!  x o                                     x  ",
   "       x       x    !!!!            !!!!!            !   x          b                  b         x  ",
   "       x!!!!!!!x    !              !!!!!!!           !!  xxxxxx  xxxxxxxxxx  xxxxxxxxxxxxxxxxx   x  ",
   "       x!!!!!!!x    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!       x  x        x  x               x   x  ",
   "       x!!!!!!!x       !   !!!!!!!    !    !!!!!!!    !       xxxx   !    xxxx      !        xxxxx  ",
   "       x!!!!!!!x      ! !   !!!!!    ! !    !!!!!    ! !            ! !            ! !              ",
   "       x!!!!!!!x     ! ! !   !!!    ! ! !    !!!    ! ! !          ! ! !          ! ! !             ",
   "       x!!!!!!!x    ! !!! !   !    ! !!! !    !    ! !!! !        ! !!! !        ! !!! !            "],
["                                                                                                           ",
  "                                                                                                           ",
  "                                                                             o                             ",
  "                                         o                                   o                             ",
  "                o                       ooo                                 xxxx                           ",
  "               xxx                     xxxxx                                                               ",
  "              x!!!x                    xxvxx   xx                b                                    o    ",
  "     o         xvx               o                    xxxxxx!!!!xxxxxxxxx!!!!xxxxxxxxxxx!!!!xx     xxxxxxx ",
  "    xxx                         xxxx                 x  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! x     x  !  x ",
  "     x                                               x  !   xxxvxxxxxxxxxxxxxxxxxxxxxxxxxx ! x     x !!! x ",
  "     x  xx        o                                 ox  !!! x        o     o     o       x ! x     x !   x ",
  "     x            o                                 x     ! x                            x ! x    xx !!! x ",
  "!!!!!x       oxxxxxxx                      b        x !!!!! x      xxxxxxxxxxxxxxxxxxx   x ! x     x   ! x ",
  "!!!!!x      xxx!!!!!x         o                     x !     x      x                 x   x ! x     x !!! x ",
  "!!!!!x        x!!!!!x         o              xxx    x !!!!! x     xx  xxxxxxxxxxxxx  x   x ! x     x !   x ",
  "!!!!!x        x!!!!!x        xxx             x x    x     ! x      x  x     o     xxxx   x ! x     x !!! x ",
  "!!!!!x o      x!!!xxx        x x      o      x x    x !!!!! x      x  x    ooo           x ! x     x   ! x ",
  "!!!!!xxx      x!!!x          x x     xxx     x x    x !     xxx    x  x     o            x ! xx    x !!! x ",
  "!!!!!x        x!!!xo         x x     x x     x x    x !!!!! x      x  xxxxxxxxxxxxxxxxxxxx ! x     x !   x ",
  "xxxxxx      xxx!!!xxxxxx     x x     x x     x x    x     ! x      x  !!!!!!!!!!!!!!!!!v!!!! x     x !!! x ",
  "              x!!!!!!!!x     x x     x x     x x    x !!!!! x    xxxxxxxxxxxxxxxxxxxxxx xxxxxx     x   ! x ",
  "  @           x!!!!!!!!x     x x     x x     x x    x !     x                   o                  x !!! x ",
  "xxxxxxxxxxxxxxx!!!!!!!!x     x x     x x     x x    x !!!!! x                  ooo                 x !   x ",
  "!!!!!!!!!!!!!!!!!!!!!!!x     x x     x x     x x    x     ! x     b                                x !!! x ",
  "!!!!!!!!!!!!!!!!!!!!!!!x!!!!!x x!!!!!x x!!!!!x x!!!!x !!!!! xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ! x ",
  "!!!!!!!!!!!!!!!!!!!!!!!x!!!!!x x!!!!!x x!!!!!x x!!!!x !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! x "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
